export interface BrandColor {
  primary: string;
  secondary?: string;
}

export const brandColors: Record<string, BrandColor> = {
  // --- Languages ---
  'typescript': {primary: '#3178C6'},
  'typescript-config': {primary: '#3178C6'},
  'typescript-def': {primary: '#3178C6'},
  'typescript-react': {primary: '#3178C6'},
  'typescript-test': {primary: '#3178C6'},
  'javascript': {primary: '#F7DF1E'},
  'javascript-config': {primary: '#F7DF1E'},
  'javascript-map': {primary: '#F7DF1E'},
  'javascript-react': {primary: '#61DAFB'},
  'javascript-test': {primary: '#F7DF1E'},
  'python': {primary: '#3776AB', secondary: '#FFD43B'},
  'python-compiled': {primary: '#3776AB'},
  'python-config': {primary: '#3776AB'},
  'rust': {primary: '#DEA584'},
  'rust-alt': {primary: '#DEA584'},
  'rust-alt-config': {primary: '#DEA584'},
  'rust-config': {primary: '#DEA584'},
  'go': {primary: '#00ADD8'},
  'go-mod': {primary: '#00ADD8'},
  'go-template': {primary: '#00ADD8'},
  'java': {primary: '#ED8B00', secondary: '#5382A1'},
  'java-alt-1': {primary: '#ED8B00'},
  'java-alt-2': {primary: '#ED8B00'},
  'java-alt-3': {primary: '#ED8B00'},
  'java-annotation': {primary: '#ED8B00'},
  'java-class': {primary: '#ED8B00'},
  'java-class-abstract': {primary: '#ED8B00'},
  'java-class-final': {primary: '#ED8B00'},
  'java-class-sealed': {primary: '#ED8B00'},
  'java-enum': {primary: '#ED8B00'},
  'java-exception': {primary: '#ED8B00'},
  'java-interface': {primary: '#ED8B00'},
  'java-jar': {primary: '#ED8B00'},
  'java-record': {primary: '#ED8B00'},
  'c': {primary: '#A8B9CC'},
  'c-header': {primary: '#A8B9CC'},
  'cpp': {primary: '#00599C'},
  'cpp-header': {primary: '#00599C'},
  'csharp': {primary: '#68217A'},
  'fsharp': {primary: '#378BBA'},
  'ruby': {primary: '#CC342D'},
  'ruby-gem': {primary: '#CC342D'},
  'ruby-gem-lock': {primary: '#CC342D'},
  'php': {primary: '#777BB4'},
  'phtml': {primary: '#777BB4'},
  'swift': {primary: '#F05138'},
  'swiftformat': {primary: '#F05138'},
  'kotlin': {primary: '#7F52FF'},
  'dart': {primary: '#00B4AB'},
  'dart-generated': {primary: '#00B4AB'},
  'scala': {primary: '#DC322F'},
  'clojure': {primary: '#5881D8'},
  'elixir': {primary: '#6E4A7E'},
  'erlang': {primary: '#A90533'},
  'haskell': {primary: '#5D4F85'},
  'lua': {primary: '#000080'},
  'lua-check': {primary: '#000080'},
  'lua-client': {primary: '#000080'},
  'lua-rocks': {primary: '#000080'},
  'lua-server': {primary: '#000080'},
  'lua-test': {primary: '#000080'},
  'luau': {primary: '#00A2FF'},
  'luau-check': {primary: '#00A2FF'},
  'luau-client': {primary: '#00A2FF'},
  'luau-config': {primary: '#00A2FF'},
  'luau-server': {primary: '#00A2FF'},
  'luau-test': {primary: '#00A2FF'},
  'perl': {primary: '#39457E'},
  'r': {primary: '#276DC3'},
  'julia': {primary: '#9558B2'},
  'nim': {primary: '#FFE953'},
  'zig': {primary: '#F7A41D'},
  'odin': {primary: '#2B5797'},
  'crystal': {primary: '#000000'},
  'v': {primary: '#5D87BF'},
  'd': {primary: '#B03931'},
  'fortran': {primary: '#734F96'},
  'cobol': {primary: '#005CA5'},
  'assembly': {primary: '#6E4C13'},
  'haxe': {primary: '#EA8220'},
  'racket': {primary: '#9F1D20'},
  'scheme': {primary: '#1E4AEC'},
  'lisp': {primary: '#3FB68B'},
  'prolog': {primary: '#74283C'},
  'ocaml': {primary: '#EC6813'},
  'reason': {primary: '#DD4B39'},
  'rescript': {primary: '#E6484F'},
  'gleam': {primary: '#FFAFF3'},
  'hare': {primary: '#D7A64E'},
  'amber': {primary: '#F7931A'},
  'solidity': {primary: '#363636'},
  'huff': {primary: '#4A90D9'},
  'coffeescript': {primary: '#2F2625'},
  'batch': {primary: '#C1F12E'},

  // --- Web ---
  'html': {primary: '#E34F26'},
  'css': {primary: '#1572B6'},
  'css3': {primary: '#1572B6'},
  'css-map': {primary: '#1572B6'},
  'sass': {primary: '#CC6699'},
  'less': {primary: '#1D365D'},
  'json': {primary: '#A8B9CC'},
  'json-schema': {primary: '#A8B9CC'},
  'xml': {primary: '#F5844C'},
  'yaml': {primary: '#CB171E'},
  'toml': {primary: '#9C4221'},
  'markdown': {primary: '#083FA1'},
  'markdown-mdx': {primary: '#F9AC00'},
  'svg': {primary: '#FFB13B'},
  'graphql': {primary: '#E10098'},
  'pug': {primary: '#A86454'},
  'ejs': {primary: '#B4CA65'},
  'handlebars': {primary: '#F0772B'},
  'nunjucks': {primary: '#1C4913'},
  'liquid': {primary: '#67B5FF'},
  'haml': {primary: '#ECE2A9'},
  'twig': {primary: '#BAC74B'},

  // --- Frameworks ---
  'angular': {primary: '#DD0031', secondary: '#C3002F'},
  'angular-component': {primary: '#DD0031'},
  'angular-directive': {primary: '#DD0031'},
  'angular-guard': {primary: '#DD0031'},
  'angular-pipe': {primary: '#DD0031'},
  'angular-service': {primary: '#DD0031'},
  'react': {primary: '#61DAFB'},
  'vue': {primary: '#42B883'},
  'vue-config': {primary: '#42B883'},
  'svelte': {primary: '#FF3E00'},
  'svelte-config': {primary: '#FF3E00'},
  'astro': {primary: '#BC52EE'},
  'astro-config': {primary: '#BC52EE'},
  'next': {primary: '#FFFFFF'},
  'nuxt': {primary: '#00DC82'},
  'nuxt-ignore': {primary: '#00DC82'},
  'gatsby': {primary: '#663399'},
  'ember': {primary: '#E04E39'},
  'remix': {primary: '#FFFFFF'},
  'solid': {primary: '#2C4F7C'},
  'qwik': {primary: '#18B6F6'},
  'django': {primary: '#092E20'},
  'laravel': {primary: '#FF2D20'},
  'nest': {primary: '#E0234E'},
  'nest-controller': {primary: '#E0234E'},
  'nest-decorator': {primary: '#E0234E'},
  'nest-filter': {primary: '#E0234E'},
  'nest-gateway': {primary: '#E0234E'},
  'nest-guard': {primary: '#E0234E'},
  'nest-middleware': {primary: '#E0234E'},
  'nest-pipe': {primary: '#E0234E'},
  'nest-service': {primary: '#E0234E'},
  'adonis': {primary: '#5A45FF'},
  'blitz': {primary: '#6700EB'},
  'redwood': {primary: '#BF4722'},

  // --- Runtimes / Package Managers ---
  'node': {primary: '#339933'},
  'nodemon': {primary: '#76D04B'},
  'bun': {primary: '#FBF0DF'},
  'bun-lock': {primary: '#FBF0DF'},
  'deno': {primary: '#FFFFFF'},
  'deno-lock': {primary: '#FFFFFF'},
  'npm': {primary: '#CB3837'},
  'npm-ignore': {primary: '#CB3837'},
  'npm-lock': {primary: '#CB3837'},
  'pnpm': {primary: '#F69220'},
  'pnpm-lock': {primary: '#F69220'},
  'yarn': {primary: '#2C8EBB'},
  'yarn-lock': {primary: '#2C8EBB'},
  'cargo': {primary: '#DEA584'},
  'cargo-lock': {primary: '#DEA584'},
  'package-json': {primary: '#339933'},
  'pixi': {primary: '#F7C832'},
  'pixi-lock': {primary: '#F7C832'},

  // --- Build / Bundlers ---
  'webpack': {primary: '#8DD6F9', secondary: '#1C78C0'},
  'vite': {primary: '#646CFF', secondary: '#FFC018'},
  'rollup': {primary: '#EC4A3F'},
  'esbuild': {primary: '#FFCF00'},
  'babel': {primary: '#F9DC3E'},
  'gulp': {primary: '#CF4647'},
  'snowpack': {primary: '#2E5E82'},
  'turbo': {primary: '#0096FF'},
  'nx': {primary: '#143055'},
  'nx-ignore': {primary: '#143055'},
  'lerna': {primary: '#9333EA'},
  'moonrepo': {primary: '#C386F0'},

  // --- Linters / Formatters ---
  'eslint': {primary: '#4B32C3', secondary: '#8080F2'},
  'eslint-ignore': {primary: '#4B32C3'},
  'prettier': {primary: '#F7B93E'},
  'prettier-ignore': {primary: '#F7B93E'},
  'stylelint': {primary: '#263238'},
  'stylelint-ignore': {primary: '#263238'},
  'biome': {primary: '#60A5FA'},
  'oxlint': {primary: '#6EDB8F'},

  // --- Testing ---
  'jest': {primary: '#C21325'},
  'vitest': {primary: '#6E9F18'},
  'cypress': {primary: '#17202C'},
  'playwright': {primary: '#2EAD33'},
  'storybook': {primary: '#FF4785'},
  'storybook-svelte': {primary: '#FF4785'},
  'storybook-vue': {primary: '#FF4785'},

  // --- DevOps / Cloud ---
  'docker': {primary: '#2496ED'},
  'docker-compose': {primary: '#2496ED'},
  'docker-ignore': {primary: '#2496ED'},
  'kubernetes': {primary: '#326CE5'},
  'terraform': {primary: '#7B42BC'},
  'opentofu': {primary: '#FFDA18'},
  'ansible-lint': {primary: '#EE0000'},
  'azure-pipelines': {primary: '#0078D7'},
  'circle-ci': {primary: '#343434'},
  'github': {primary: '#FFFFFF'},
  'gitlab': {primary: '#FC6D26'},
  'bitbucket': {primary: '#0052CC'},
  'vercel': {primary: '#FFFFFF'},
  'vercel-ignore': {primary: '#FFFFFF'},
  'netlify': {primary: '#00C7B7'},
  'firebase': {primary: '#FFCA28'},
  'gcp': {primary: '#4285F4'},
  'heroku': {primary: '#430098'},
  'serverless': {primary: '#FD5750'},
  'nginx': {primary: '#009639'},
  'apache': {primary: '#D22128'},
  'caddy': {primary: '#00ADD8'},

  // --- Databases ---
  'database': {primary: '#F29111'},
  'prisma': {primary: '#2D3748'},
  'drizzle-orm': {primary: '#C5F74F'},

  // --- Git / VCS ---
  'git': {primary: '#F05032'},
  'git-cliff': {primary: '#F05032'},
  'gitpod': {primary: '#FFAE33'},

  // --- Mobile ---
  'android': {primary: '#3DDC84'},
  'flutter': {primary: '#02569B'},
  'ionic': {primary: '#3880FF'},
  'capacitor': {primary: '#119EFF'},
  'nativescript': {primary: '#65ADF1'},
  'tauri': {primary: '#FFC131'},
  'tauri-ignore': {primary: '#FFC131'},

  // --- Editors / IDEs ---
  'vscode': {primary: '#007ACC'},
  'vscode-ignore': {primary: '#007ACC'},
  'vs-codium': {primary: '#2F80ED'},
  'visual-studio': {primary: '#5C2D91'},
  'sublime': {primary: '#FF9800'},
  'cursor': {primary: '#FFFFFF'},
  'cursor-ignore': {primary: '#FFFFFF'},

  // --- Infra / Config ---
  'nix': {primary: '#5277C3'},
  'nix-lock': {primary: '#5277C3'},
  'cmake': {primary: '#064F8C'},
  'makefile': {primary: '#6D8086'},
  'gradle': {primary: '#02303A'},
  'bazel': {primary: '#43A047'},
  'meson': {primary: '#007EC6'},

  // --- Data ---
  'csv': {primary: '#237346'},
  'excel': {primary: '#217346'},

  // --- Media ---
  'image': {primary: '#8BC34A'},
  'video': {primary: '#FF5722'},
  'audio': {primary: '#FF9100'},
  'font': {primary: '#F54D27'},
  '3d': {primary: '#FF6F00'},
  'pdf': {primary: '#F40F02'},

  // --- Adobe ---
  'adobe-ae': {primary: '#9999FF'},
  'adobe-ai': {primary: '#FF9A00'},
  'adobe-id': {primary: '#FF3366'},
  'adobe-ps': {primary: '#31A8FF'},
  'adobe-xd': {primary: '#FF61F6'},

  // --- Apple / Microsoft ---
  'apple': {primary: '#A2AAAD'},
  'ms-word': {primary: '#2B579A'},
  'ms-excel': {primary: '#217346'},
  'ms-powerpoint': {primary: '#D24726'},

  // --- Documentation ---
  'readme': {primary: '#83B81A'},
  'changelog': {primary: '#00BCD4'},
  'license': {primary: '#F5C211'},
  'contributing': {primary: '#4CAF50'},
  'code-of-conduct': {primary: '#E91E63'},
  'todo': {primary: '#FFAB40'},
  'security': {primary: '#FF5252'},

  // --- Shell ---
  'bash': {primary: '#4EAA25'},
  'powershell': {primary: '#5391FE'},
  'batch': {primary: '#C1F12E'},
  'zsh': {primary: '#4EAA25'},

  // --- Config / Misc ---
  'env': {primary: '#ECD53F'},
  'envrc': {primary: '#ECD53F'},
  'editorconfig': {primary: '#FEFEFE'},
  'browserslist': {primary: '#FFC107'},
  'commitlint': {primary: '#FFFFFF'},
  'lint-staged': {primary: '#FFC107'},
  'husky': {primary: '#42A5F5'},
  'dependabot': {primary: '#0366D6'},
  'renovate': {primary: '#1A1F6C'},
  'semantic-release': {primary: '#494949'},
  'sentry': {primary: '#362D59'},

  // --- Markup / Templating ---
  'latex': {primary: '#008080'},
  'typst': {primary: '#239DAD'},
  'asciidoc': {primary: '#E40046'},
  'org': {primary: '#77AA99'},
  'mermaid': {primary: '#FF3670'},
  'plantuml': {primary: '#BFCD56'},

  // --- Misc Tools ---
  'godot': {primary: '#478CBF'},
  'godot-assets': {primary: '#478CBF'},
  'unity': {primary: '#FFFFFF'},
  'arduino': {primary: '#00878F'},
  'wasm': {primary: '#654FF0'},
  'web-assembly': {primary: '#654FF0'},
  'figma': {primary: '#F24E1E'},
  'sketch': {primary: '#FDAD00'},
  'drawio': {primary: '#F08705'},
  'http': {primary: '#005C9C'},
  'robots': {primary: '#8BC34A'},
  'panda-css': {primary: '#FDE047'},
  'tailwind': {primary: '#06B6D4'},
  'windi': {primary: '#48B0F1'},
  'postcss': {primary: '#DD3A0A'},
  'vanilla-extract': {primary: '#99E3F3'},
  'unocss': {primary: '#909399'},
  'stitches': {primary: '#FFFFFF'},
  'styled': {primary: '#DB7093'},

  // --- Hosting / Deploy ---
  'wrangler': {primary: '#F48120'},

  // --- Other Languages ---
  'verilog': {primary: '#B2B7F8'},
  'matlab': {primary: '#E16737'},
  'stata': {primary: '#1A5F91'},
  'cuda': {primary: '#76B900'},
  'groovy': {primary: '#4298B8'},
  'puppet': {primary: '#FFAE1A'},
  'bicep': {primary: '#0078D4'},
  'helm': {primary: '#0F1689'},
};
