// Parses vscode-icons mapping data into a generated vsci-data.ts file.
// Run: tsx scripts/file-icons/sync-vscode-icons.ts

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '../..');
const VSCI_SRC = path.join(ROOT, 'vendor/vscode-icons/src/iconsManifest');
const VSCI_ICONS = path.join(ROOT, 'vendor/vscode-icons/icons');
const OUT_FILE = path.join(__dirname, 'vsci-data.ts');

interface LangEntry {
  ids: string | string[];
  knownExtensions: string[];
}

interface RawFileEntry {
  icon: string;
  extensions: string[];
  filename?: boolean;
  languages?: LangEntry[];
  disabled?: boolean;
}

interface RawFolderEntry {
  icon: string;
  extensions: string[];
  disabled?: boolean;
}

interface VsciCollection<T> {
  default: unknown;
  supported: T[];
}

const FILE_FORMAT = {svg: 0, png: 1, jpg: 2, gif: 3, bmp: 4, tiff: 5, ico: 6};

function stripTs(text: string): string {
  return text
    .replace(/^import\s.*$/gm, '')
    .replace(/\}\s*satisfies\s+[^;]+;/g, '};')
    .replace(/:\s*(?:IFileCollection|IFolderCollection|ILanguage)\b/g, '')
    .replace(/export\s+const\s+(\w+)/g, 'var $1');
}

function parseLanguages(): Record<string, LangEntry> {
  const body = stripTs(fs.readFileSync(path.join(VSCI_SRC, 'languages.ts'), 'utf-8'));
  // eslint-disable-next-line no-new-func
  return new Function(body + '\nreturn languages;')() as Record<string, LangEntry>;
}

function parseExtensions(languages: Record<string, LangEntry>): RawFileEntry[] {
  const body = stripTs(fs.readFileSync(path.join(VSCI_SRC, 'supportedExtensions.ts'), 'utf-8'));
  // eslint-disable-next-line no-new-func
  const result = new Function('languages', 'FileFormat', body + '\nreturn extensions;')(languages, FILE_FORMAT) as VsciCollection<RawFileEntry>;
  return result.supported ?? [];
}

function parseFolders(): RawFolderEntry[] {
  const body = stripTs(fs.readFileSync(path.join(VSCI_SRC, 'supportedFolders.ts'), 'utf-8'));
  // eslint-disable-next-line no-new-func
  const result = new Function('FileFormat', body + '\nreturn extensions;')(FILE_FORMAT) as VsciCollection<RawFolderEntry>;
  return result.supported ?? [];
}

function parseLangIds(lang: LangEntry): string[] {
  return Array.isArray(lang.ids) ? lang.ids : [lang.ids];
}

function svgExists(name: string): boolean {
  return fs.existsSync(path.join(VSCI_ICONS, name));
}

function sync(): void {
  console.log('Syncing vscode-icons mapping data...');

  const languages = parseLanguages();
  console.log(`  Parsed ${Object.keys(languages).length} language entries`);

  const rawFiles = parseExtensions(languages);
  console.log(`  Parsed ${rawFiles.length} raw file entries`);

  const rawFolders = parseFolders();
  console.log(`  Parsed ${rawFolders.length} raw folder entries`);

  const fileEntries: string[] = [];
  let fileSkipped = 0;

  for (const entry of rawFiles) {
    if (entry.disabled) {
      continue;
    }

    const svgName = `file_type_${entry.icon}.svg`;
    if (!svgExists(svgName)) {
      fileSkipped++;
      continue;
    }

    const extensions: string[] = [];
    const fileNames: string[] = [];
    const languageIds: string[] = [];

    if (entry.filename) {
      for (const e of entry.extensions) {
        fileNames.push(e);
      }
    } else {
      for (const e of entry.extensions) {
        extensions.push(e);
      }
    }

    if (entry.languages) {
      for (const lang of entry.languages) {
        for (const id of parseLangIds(lang)) {
          if (!languageIds.includes(id)) {
            languageIds.push(id);
          }
        }
      }
    }

    fileEntries.push(
      `  {icon: ${JSON.stringify(entry.icon)}, extensions: ${JSON.stringify(extensions)}, fileNames: ${JSON.stringify(fileNames)}, languageIds: ${JSON.stringify(languageIds)}},`,
    );
  }

  const folderEntries: string[] = [];
  let folderSkipped = 0;

  for (const entry of rawFolders) {
    if (entry.disabled) {
      continue;
    }

    const svgName = `folder_type_${entry.icon}.svg`;
    if (!svgExists(svgName)) {
      folderSkipped++;
      continue;
    }

    folderEntries.push(
      `  {icon: ${JSON.stringify(entry.icon)}, folderNames: ${JSON.stringify(entry.extensions)}},`,
    );
  }

  const output = `// AUTO-GENERATED by sync-vscode-icons.ts -- do not edit manually
// Source: vendor/vscode-icons (${new Date().toISOString().slice(0, 10)})

export interface VsciFileEntry {
  icon: string;
  extensions: string[];
  fileNames: string[];
  languageIds: string[];
}

export interface VsciFolderEntry {
  icon: string;
  folderNames: string[];
}

export const vsciFiles: VsciFileEntry[] = [
${fileEntries.join('\n')}
];

export const vsciFolders: VsciFolderEntry[] = [
${folderEntries.join('\n')}
];
`;

  fs.writeFileSync(OUT_FILE, output);

  console.log(`  ${fileEntries.length} file icons (${fileSkipped} skipped, no SVG)`);
  console.log(`  ${folderEntries.length} folder icons (${folderSkipped} skipped, no SVG)`);
  console.log(`  Written to ${path.relative(ROOT, OUT_FILE)}`);
}

sync();
